# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
    ports:
      - 3306:3306

  adminer:
    container_name: adminer-mariadb
    image: adminer
    restart: always
    ports:
      - 8080:8080